server:
    port: 3000
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://stocktrading.cvklzmyema33.us-east-2.rds.amazonaws.com/stocktradingdb?allowPublicKeyRetrieval=true&useSSL=false
        username: root
        password: abc123456
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        properties:
            hibernate:
                format_sql: true
                enable_lazy_load_no_trans: true
    jackson:
        serialization:
            fail-on-empty-beans: false
secretKey: fPJZz!YkEmUhdmvvhw7y*6K*0$7vco!pfiOtq6N&cgnLNT$I4u

